medida = float(input('Digite um valor em metros: '))
print(f'Para o valor de {medida}m, têm-se as seguintes conversões: ')
print('='*56)
print(f'{medida/1000:.2f}km')
print(f'{medida/100:.2f}hm')
print(f'{medida/10:.2f}dam')
print(f'{medida*1:.2f}m')
print(f'{medida*10:.2f}dm')
print(f'{medida*100:.2f}cm')
print(f'{medida*1000:.2f}mm')
